### ISSUE TITLE
Tekuti fails to start -- take 2

### ISSUE THREAD

**Issue by k4r4b3y** [wingo/tekuti#4]
Cloning the repo to the following directory: `~/Documents/blog/test-tekuti` and then chaging the dir into it:

```zsh
cd ~/Documents/blog/test-tekuti; autoreconf -vif; ./configure && make
./env src/tekuti
```

I am getting the following error:

```
[workstation user ~/Documents/blog/test-tekuti]% ./env src/tekuti

;;; (reading-index)
fatal: ambiguous argument 'refs/heads/index': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'refs/heads/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Backtrace:
In ice-9/boot-9.scm:
  1752:10  8 (with-exception-handler _ _ #:unwind? _ # _)
In unknown file:
           7 (apply-smob/0 #<thunk 7a7a7770f360>)
In ice-9/boot-9.scm:
    724:2  6 (call-with-prompt _ _ #<procedure default-prompt-handle…>)
In ice-9/eval.scm:
    619:8  5 (_ #(#(#<directory (guile-user) 7a7a77712c80>)))
In ice-9/command-line.scm:
   185:19  4 (_ #<input: string 7a7a7770c850>)
In unknown file:
           3 (eval ((@ (tekuti boot) boot) (program-arguments)) #<di…>)
In tekuti/web.scm:
    97:15  2 (main-loop)
In tekuti/index.scm:
   108:16  1 (maybe-reindex ())
In tekuti/git.scm:
    111:2  0 (git-rev-parse _)

tekuti/git.scm:111:2: In procedure git-rev-parse:
ERROR:
  1. &git-condition:
      argv: ("git" "--bare" "rev-parse" "refs/heads/master")
      output: "refs/heads/master\n"
      status: 32768
zsh: exit 1     ./env src/tekuti
```
This issue was reported here: https://github.com/wingo/tekuti/issues/2
The OP suggests `rm -fr ~/blog.git` and retrying.  But doing those didn't solve my issue.  I don't see tekuti on `localhost:8080` in my browser.

----

I am trying this on whonix-workstation-17 (debian-12 based), with the following packages installed from the debian stable repos:
```
guile-3.0 guile-3.0-dev elpa-geiser
```

**Comment by ray1729** [comment]
@k4r4b3y disclaimer: I have no prior knowledge of tekuti, but I was intrigued when you asked on IRC and took a look. Some of the git errors that appear in the log are expected and handled by the code, but one problem I ran into is that the code assumes `git init` will create a `master` branch:  I have some local config that defaults this to `main`. Updating the code to do `git init -b master`  solved that problem. Once this was fixed I ran into an issue with `list-posts` that was easily fixed by defaulting to an empty list when there are no `posts-by-date` in the index.

```
diff --git a/tekuti/git.scm b/tekuti/git.scm
index cad4e0c..25dde39 100644
--- a/tekuti/git.scm
+++ b/tekuti/git.scm
@@ -125,7 +125,7 @@
         (begin
           (mkdir d)
           (chdir d)
-          (git "init")
+          (git "init" "-b" "master")
           (git "update-ref" "refs/heads/master"
                (git-commit-tree (string-trim-both (git* '("mktree") #:input ""))
                                 #f "initial commit" #f)))
diff --git a/tekuti/post.scm b/tekuti/post.scm
index e13bb40..92f687c 100644
--- a/tekuti/post.scm
+++ b/tekuti/post.scm
@@ -273,7 +273,7 @@
    (lambda (key)
      (and=> (post-from-key index key #:allow-unpublished? allow-unpublished?)
             (lambda (post) (and (filter post) post))))
-   (assq-ref index 'posts-by-date)
+   (or (assq-ref index 'posts-by-date) '())
    limit))
 
 (define (reindex-posts old-index index)
```

**Comment by k4r4b3y** [comment]
@ray1729 thanks for the reply.

>but one problem I ran into is that the code assumes git init will create a master branch: I have some local config that defaults this to main. Updating the code to do git init -b master solved that problem. 

That's interesting.  However, in my debian system, I have not specifically changed the name of the default branch that gets created when `git init` command is applied.  Therefore, I don't think this is relevant to my problem -- still thanks for pointing it out, as it may help others reading this thread!

 >Once this was fixed I ran into an issue with list-posts that was easily fixed by defaulting to an empty list when there are no posts-by-date in the index.

That's interesting, I will keep this in mind.

----

The real problem I am having is, even if I somehow get the tekuti running, I still get some error messages in its stdout, something about path `metadata` not existing for some of the git blobs.  Apart from that, as tekuti is running in my terminal, I visit http://localhost:8080, and all I see is an empty page -- according to tekuti's sole [setup guide](https://www.wingolog.org/projects/tekuti/) I should see "something".  Further, in order to add the first, the initial post to my tekuti blog, I try and visit http://localhost:8080/blog/admin, which, according to the aforementioned setup guide, should show me an admin UI for adding a new post -- which I don't get.

Do you get to the admin UI for adding a new post with your tekuti setup?

**Comment by ray1729** [comment]
@k4r4b3y To eliminate oddities in my local configuration I ran everything in a clean `debian:bookworm` container. I use podman but you could equally use Docker: `podman run --name tekuti -i -t -p 8080:8080 debian:bookworm`. 

Inside the container, I ran the following:
```
apt-get -qq update && apt-get -qq install git git-lfs guile-3.0 guile-3.0-dev make
git clone https://github.com/wingo/tekuti
cd tekuti/
autoreconf -vif
./configure
make
git config --global user.email contact@1729.org.uk
git config --global user.name "Ray Miller"
./env src/tekuti
```
Now, when I visit http://localhost:8080/ I see a blank page and in browser dev tools it shows the server returning status 500. The significant error in the terminal is: 

```
Error log: In procedure car: Wrong type argument in position 1 (expecting pair): #f
```

I did some debugging in the guile repl and traced it to the `filter-mapn` function in `tekuti/util.scm`. This is called by `latest-posts` in `tekuti/post.scm`. The problem is, for a new blog the index is empty so `(assq-ref index 'posts-by-date)` returns `#f` which gets passed to `filter-mapn` which then calls `car` which triggers the exception. The patch I first suggested replaces that argument to the call with `(or (assq-ref index 'posts-by-date) '())` so it passes in an empty list instead of `#f`. After a bit more thought, a better fix would be to update `filter-mapn` to guard against a `#f` arg when it's expecting a list. This can be done by:

```
diff --git a/tekuti/util.scm b/tekuti/util.scm
index 2a6d6fb..46fdec0 100644
--- a/tekuti/util.scm
+++ b/tekuti/util.scm
@@ -160,7 +160,7 @@
 
 (define (filter-mapn proc l nmax)
   (let lp ((in l) (out '()) (n nmax))
-    (if (or (null? in) (zero? n))
+    (if (or (nil? in) (zero? n))
         (reverse out)
         (let ((val (proc (car in))))
           (if val
```

If I make that change then run `./env src/tekuti` and visit http://localhost:8080 I now see a blog and if I visit http://localhost:8080/admin and login as admin/admin, I get a form where I can create a post. I verified that I can create a post, make it public, then visited the home page and saw the post. So I think this simple fix suggested above will address your problem.

**Comment by k4r4b3y** [comment]
@ray1729 applying this single patch (which changes `null?` to `nil?`) and then running 
```
cd tekuti; autoreconf -vif; ./configure && make
./env src/tekuti
```
prints out the following in the stdout:
```

;;; (reading-index)
fatal: ambiguous argument 'refs/heads/index': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'refs/heads/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Backtrace:
In ice-9/boot-9.scm:
  1752:10  8 (with-exception-handler _ _ #:unwind? _ # _)
In unknown file:
           7 (apply-smob/0 #<thunk 7269e250f360>)
In ice-9/boot-9.scm:
    724:2  6 (call-with-prompt _ _ #<procedure default-prompt-handle…>)
In ice-9/eval.scm:
    619:8  5 (_ #(#(#<directory (guile-user) 7269e2512c80>)))
In ice-9/command-line.scm:
   185:19  4 (_ #<input: string 7269e250c850>)
In unknown file:
           3 (eval ((@ (tekuti boot) boot) (program-arguments)) #<di…>)
In tekuti/web.scm:
    97:15  2 (main-loop)
In tekuti/index.scm:
   108:16  1 (maybe-reindex ())
In tekuti/git.scm:
    111:2  0 (git-rev-parse _)

tekuti/git.scm:111:2: In procedure git-rev-parse:
ERROR:
  1. &git-condition:
      argv: ("git" "--bare" "rev-parse" "refs/heads/master")
      output: "refs/heads/master\n"
      status: 32768
zsh: exit 1     ./env src/tekuti
```
Implicit to all of these steps, I am guessing I need to create a ~/blog directory, and then initialize a git in there?

**Comment by k4r4b3y** [comment]
I just noticed that me cloning the repo to ~/Documents/tekuti and not into ~/tekuti was causing my abovementioned issue.  What a bummer and an annoyance!

**Comment by ray1729** [comment]
There's no need to create the blog directory, tekuti will do that automatically on start-up. It might be worth running `rm -rf ~/blog.git` in case you have something leftover from an earlier attempt.

**Comment by ray1729** [comment]
> I just noticed that me cloning the repo to ~/Documents/tekuti and not into ~/tekuti was causing my abovementioned issue. What a bummer and an annoyance!

I don't think that explains your problem, it worked for me when I checked it out to `~/Workspace/scratch/tekuti`.

A lot of the git errors you see in the log are benign, many of the calls are wrapped in a guard that returns `#f` when a git error is encountered (which happens when objects don't exist yet).  I'm puzzled as to why the error about `git rev-parse` is fatal in your case: I see the same error but it is trapped and the code carries on.

**Comment by k4r4b3y** [comment]
@ray1729 following your comment [here](https://github.com/wingo/tekuti/issues/4#issuecomment-2455669169) **exactly and step by step** allowed me to also reach the tekuti's homepage (localhost:8080) and also to the admin page (localhost:8080/admin) and add a new post, then see it in the mainpage.

Thank you for your simple patch in the abovelinked comment.  Now, I will play with tekuti a while, and see how it works for me.  Apart from that, I think I can close this issue now.
